### ISSUE TITLE
java inner class issue

### ISSUE THREAD

**Issue by ChanningZhang** [shuzijun/plantuml-parser#17]
**Describe the bug**
below class definition will lead an error: bad hierarchy for class CustomSqlValidator.LazyHolder

class CustomSqlValidator.LazyHolder {
+ {static} CustomSqlValidator INSTANCE
}

**Software versions(*Help* -> *About*)**
- IDEA 2023.1
- parser version: 0.04

**Comment by shuzijun** [comment]
Can you provide a complete example?

**Comment by ChanningZhang** [comment]
here is a very simple example as below:
`public class OutterClass {
    public String id;
  

    public class InnerClass{
        public String field1;
    }
}
`
exception shows:
![image](https://user-images.githubusercontent.com/8260328/235904836-c50ee869-4da7-4c76-9f7f-ec4e8fb387de.png)

**Comment by ChanningZhang** [comment]
issue was NOT resolved
