### ISSUE TITLE
hope to support kotlin

### ISSUE THREAD

**Issue by CHENQINGFU** [shuzijun/plantuml-parser#18]
**Desc**
Start a discussion or ask for help

**Software versions(*Help* -> *About*)(Optional)**
- Product: [e.g IDEA 2020.2]
- Runtime version:[e.g 11.0.7+10-b944.20 amd64]
- VM:[e.g OpenJDK 64-Bit Server VM by JetBrains s.r.o.]
- OS:[e.g Windows 10]

**Question(Optional)**
- URL:[e.g leetcode.com]
- Code Type:[e.g JAVA]
- code:
  ```
  
  ```

**Comment by shuzijun** [comment]
We tried to add parsing, but there are too few documents. Those who know the syntax better can continue to develop based on this branch.

https://github.com/shuzijun/plantuml-parser/tree/feat/kt

**Comment by CHENQINGFU** [comment]
已收到邮件。
