### ISSUE TITLE
Kotlin - Generic Arguments are not able to be viewed - Syntax Error?

### ISSUE THREAD

**Issue by BoydyBoydy** [shuzijun/plantuml-parser#24]
**Describe the bug**
After generating the puml file, errors come up for 'Syntax Error?'
This seems to be due to the Class Generic Arguments.

Example - Code:
`DataRepository<T>` - Generic
`class StringDataRepository : DataRepository<String>`

Example - Generated PUML
`DataRepository<String> <|.. StringDataRepository` Typed Generic linking to the subclass -- Getting errors here

**To Reproduce**
1. Setup a Generic Data Type -- if it is just to test the parser, maybe skip this step.
2. Implement a Subclass that uses the Generic Class and a specific Data Type, i.e. String
3. Verify that the class is similar to `class StringDataRepository : DataRepository<String>`
4. Run the UML Generation
5. Verify that the error has occurred - Green UML Error Screen, instead of actual UML Diagram

I tried this with just the above example it seemed to show the error.

**Software versions(*Help* -> *About*)**
- Product: IDEA 2023.2.4 CE
- Runtime version: 17.0.8.1+7-b1000.32 amd64
- VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
- OS: Windows 10

**Comment by shuzijun** [comment]
Can you provide some specific sample code?

**Comment by BoydyBoydy** [comment]
Sure :)

Just to note everything else seems to work. Generics are still captured within UML.
When I comment out the <T> connections/lines the output continues to work as expected.

Below is Code and Parser Output.

Test Code:
```
interface Repository<T> {
    fun findAll(): Array<T>
}

class CustomRepo: Repository<String> {
    override fun findAll(): Array<String> {
        return arrayOf("Sorted1, Sorted2")
    }
}
fun main() {
    val customRepo = CustomRepo()
    println(customRepo.findAll().joinToString())
}
```

Test Parser Output:
```
@startuml
interface Repository {
+ Array<T> findAll()
}
class CustomRepo {
+ Array<String> findAll()
}


Repository<String> <|.. CustomRepo
@enduml
```
It looks like the connection to the \<T\> doesn't seem to work, but I will let you decide what the actual problem is.
Thanks.
