### ISSUE TITLE
UML can't be rendered bc plugin generates attached `note top of..` after the relevant object.

### ISSUE THREAD

**Issue by fromSmolsoft** [shuzijun/plantuml-parser#28]
**Describe the bug**
Plugin generates attached `note` after the relevant object. As result, instead of diagrams only green text is rendered and "syntax" warning is reported at closing tag `end note` saying " "  

This is what plugin generates and it doesn't get rendered properly; 
```uml
'this the object
class com.example.app.ui.MainActivity{
}
'the note with syntax warning
note top of com.example.app.ui.MainActivity
 Comets from java code are shown here.
end note
```

This is how it can be fixed by switching positions of ; 
```uml
'the note with syntax warning
note top of com.example.app.ui.MainActivity
 Comets from java code are shown here.
end note

'this the object
class com.example.app.ui.MainActivity{
}
'the note with syntax warning
note top of com.example.app.ui.MainActivity
 Comets from java code are shown here.
end note
```

**To Reproduce**
1. Go to `Project` tree
2. Right click on any packages that includes multiple sub-packages and/or classes with comments / javadocs  
3.  click `PlantUML parser` and generate uml
4. Open generated uml in Intellij / Android Studio rendered view
5. Instead of diagrams , there's only green text and uml code reports systax error at first problematic `note top of...  note end`
Note: Only some of the notes are generated this (incorrect) way. 

**Software versions(*Help* -> *About*)**
- Product: Android Studio Hedgehog | 2023.1.1 Patch 2
- Runtime version: 17.0.7+0-b2043.56-10550314 amd64
- VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.

If i misunderstood the functionally accept my apology and feel free to close the issue.

**Comment by shuzijun** [comment]
<img width="1240" alt="image" src="https://github.com/shuzijun/plantuml-parser/assets/27667179/cc83ea10-3db7-4162-9b6d-94d08ab9a74d">
I have tested the provided content and it can be displayed normally. Can you provide the source code for generating UML?

**Comment by fromSmolsoft** [comment]
> <img alt="image" width="1240" src="https://private-user-images.githubusercontent.com/27667179/306974079-cc83ea10-3db7-4162-9b6d-94d08ab9a74d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg2MDg2OTAsIm5iZiI6MTcwODYwODM5MCwicGF0aCI6Ii8yNzY2NzE3OS8zMDY5NzQwNzktY2M4M2VhMTAtM2RiNy00MTYyLTliNmQtOTRkMDhhYjlhNzRkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIyVDEzMjYzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY5OWZhNDU1ZWM5ZjJkNjM0MWEzMmU4YjU3ZDlkNDIxYTQ5YmZiYjY3OTBlNjk3ZjVhYmFjOTQxZGQyYzg0YjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.oyu-yE-XTYTYRfJY-8HWDGDk9iZsLigIoKMTYSZAXtE"> I have tested the provided content and it can be displayed normally. Can you provide the source code for generating UML?

I can't provide full project source but i tracked the issue into specific class.  


Bellow is the code snippet how the uml is generated from the class - notice the `note` not being on it's own line.  It causes all the following notes to get the syntax warning i described before.  

```uml
'Rest of the uml code...

class com.example.module_name.game.Calculator {
+ {static} int[] calculate(int,int,String)
}note left of com.example.module_name.game.Calculator::calculate(int,int,String)

     * Calculates the result of a math operation.
     * @return array where<p> int[0] = math result<p> int [1] = reminder of math operation

end note

'Rest of the uml code...
```

This is how the class looks like in Java. 

```Java
public class Calculator {
    
    /**
     * Calculates the result of a math operation.
     * @return array where<p> int[0] = math result<p> int [1] = reminder of math operation
     */
    public static int[] calculate(int num1, int num2, String operator) {
         // some code...
        return result;
    }
}
```
