### ISSUE TITLE
How to change export directory of puml?

### ISSUE THREAD

**Issue by VNRARA** [shuzijun/plantuml-parser#7]
**Desc**

How to change directory of output puml? I can't find it anywhere.

**Software versions(*Help* -> *About*)(Optional)**
- Product: [e.g IDEA 2020.2]
- Runtime version:[e.g 11.0.7+10-b944.20 amd64]
- VM:[e.g OpenJDK 64-Bit Server VM by JetBrains s.r.o.]
- OS:[e.g Windows 10]

**Question(Optional)**
- URL:[e.g leetcode.com]
- Code Type:[e.g JAVA]
- code:
  ```
  
  ```

**Comment by shuzijun** [comment]
Only support in the directory of the current project, you can enter a subdirectory in "File Name".

**Comment by VNRARA** [comment]
That's the first thing i tried, but it gave me an error

**Comment by shuzijun** [comment]
Provide error information

**Comment by VNRARA** [comment]
I found that it's tricky to get right, but it seems to work.
